# Generated by Django 5.0.14 on 2026-08-20 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('orgstructure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sub_division',
            field=models.ForeignKey(blank=True, help_text='Which SubDivision this user runs, for Sub-Branch Officers (Phase 2c).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='orgstructure.subdivision'),
        ),
    ]
