# Generated by Django 5.0.14 on 2026-08-20 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgstructure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Correspondence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('subject', models.CharField(max_length=300)),
                ('sender_name', models.CharField(max_length=200)),
                ('sender_address', models.TextField(blank=True)),
                ('date_received', models.DateField()),
                ('received_via', models.CharField(blank=True, help_text='e.g. Post, Hand delivery, Email, Fax.', max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('pending', 'Pending'), ('closed', 'Closed')], default='new', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_holder', models.ForeignKey(blank=True, help_text="The specific Subject Officer currently holding this letter, if it's reached that tier.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_correspondence', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correspondence', to='orgstructure.department')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondence', to='orgstructure.division')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_correspondence', to=settings.AUTH_USER_MODEL)),
                ('sub_division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondence', to='orgstructure.subdivision')),
            ],
            options={
                'verbose_name_plural': 'Correspondence',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('register', 'Registered'), ('forward', 'Forwarded'), ('mark_pending', 'Marked pending'), ('close', 'Closed')], max_length=20)),
                ('sub_branch_tier_enabled_snapshot', models.BooleanField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('correspondence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_events', to='correspondence.correspondence')),
                ('to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='orgstructure.department')),
                ('to_division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='orgstructure.division')),
                ('to_sub_division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='orgstructure.subdivision')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
