# Generated by Django 5.0.14 on 2026-08-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0003_correspondenceattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationcounter',
            name='kind',
            field=models.CharField(choices=[('in', 'Incoming'), ('out', 'Outgoing')], default='in', max_length=3),
        ),
        migrations.AlterField(
            model_name='registrationcounter',
            name='year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='registrationcounter',
            constraint=models.UniqueConstraint(fields=('year', 'kind'), name='unique_registration_counter_year_kind'),
        ),
    ]
