# Generated by Django 5.0.14 on 2026-08-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0005_outgoingcorrespondence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routingevent',
            name='action',
            field=models.CharField(choices=[('register', 'Registered'), ('edit', 'Edited'), ('forward', 'Forwarded'), ('reassign', 'Reassigned'), ('mark_pending', 'Marked pending'), ('close', 'Closed')], max_length=20),
        ),
    ]
