# Generated by Django 5.0.14 on 2026-08-20 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_code', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TenantWorkflowConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_branch_tier_enabled', models.BooleanField(default=True, help_text="Whether this organisation's correspondence workflow includes the Sub-Branch tier (Head of Branch → Sub-Branch → Subject Officer) or skips straight from Head of Branch to Subject Officer. Safe to change at any time — in-flight letters keep following the rules that were active when they reached their current step (Section 10, Q2).")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Workflow configuration',
                'verbose_name_plural': 'Workflow configuration',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='orgstructure.department')),
            ],
            options={
                'ordering': ['department__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_divisions', to='orgstructure.division')),
            ],
            options={
                'verbose_name_plural': 'Sub-divisions',
                'ordering': ['division__department__name', 'division__name', 'name'],
            },
        ),
    ]
